package com.isi.historique.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SearchHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAllPropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertSearchHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSearchHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAllUpdatablePropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertSearchHistoryUpdatableFieldsEquals(expected, actual);
        assertSearchHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryAutoGeneratedPropertiesEquals(SearchHistory expected, SearchHistory actual) {
        assertThat(actual)
            .as("Verify SearchHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryUpdatableFieldsEquals(SearchHistory expected, SearchHistory actual) {
        assertThat(actual)
            .as("Verify SearchHistory relevant properties")
            .satisfies(a -> assertThat(a.getSearchDate()).as("check searchDate").isEqualTo(expected.getSearchDate()))
            .satisfies(a -> assertThat(a.getRequest()).as("check request").isEqualTo(expected.getRequest()))
            .satisfies(a -> assertThat(a.getResponseDate()).as("check responseDate").isEqualTo(expected.getResponseDate()))
            .satisfies(a -> assertThat(a.getResponseDay()).as("check responseDay").isEqualTo(expected.getResponseDay()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSearchHistoryUpdatableRelationshipsEquals(SearchHistory expected, SearchHistory actual) {
        // empty method
    }
}
